# Sticrix - Codemagic CI/CD（捨て写 C:\ws\sutesho の codemagic.yaml を参考にした Sticrix 用）
# 事前に Codemagic UI で: Code signing identities に iOS 証明書・プロファイル（com.Akifumi.H.sticrix および com.Akifumi.H.sticrix.*）
#
# ★ Sticrix 用に必ず変更すること:
#   - APP_STORE_APPLE_ID: Sticrix の App Store Connect「App 情報」→ Apple ID（数字）に置き換え
#   - app_store_connect: 捨て写と同じキーなら Codemagic_App、別名なら Codemagic の「Manage keys」の名前と一致させる
#   - email.recipients: 通知を受け取るメールアドレスに変更

workflows:
  ios-sticrix:
    name: Sticrix iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.Akifumi.H.sticrix
      vars:
        BUNDLE_ID: "com.Akifumi.H.sticrix"
        # ★ 要変更: Sticrix の App Store Connect > アプリ > 一般 > App 情報 の「Apple ID」に置き換え
        APP_STORE_APPLE_ID: "6758619621"
      node: 20
      xcode: 16.4
      cocoapods: default
    integrations:
      app_store_connect: Codemagic_App
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: master
          include: true
          source: true
    scripts:
      - name: npm 依存関係のインストール
        script: |
          npm ci
      - name: Expo Prebuild (iOS)
        script: |
          npx expo prebuild --platform ios --clean
      - name: Info.plist に ITSAppUsesNonExemptEncryption を設定
        script: |
          PLIST="$CM_BUILD_DIR/ios/Sticrix/Info.plist"
          if [ -f "$PLIST" ]; then
            /usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" "$PLIST" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Set :ITSAppUsesNonExemptEncryption false" "$PLIST"
          fi
      - name: CocoaPods のインストール
        script: |
          cd ios && pod install
      - name: ビルド番号のインクリメント（オプション）
        script: |
          cd "$CM_BUILD_DIR/ios"
          if command -v app-store-connect &>/dev/null && [ -n "$APP_STORE_APPLE_ID" ] && [ "$APP_STORE_APPLE_ID" != "YOUR_APP_STORE_CONNECT_APP_ID" ]; then
            LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" 2>/dev/null) || true
            if [ -n "$LATEST" ] && [ "$LATEST" -ge 0 ] 2>/dev/null; then
              NEW=$((LATEST + 1))
            else
              NEW=$((3 + ${BUILD_NUMBER:-0}))
            fi
            agvtool new-version -all "$NEW" 2>/dev/null || true
          fi
      - name: コード署名の設定
        script: xcode-project use-profiles
      - name: IPA ビルド（ワークスペース・スキームは prebuild 結果から自動検出）
        script: |
          cd "$CM_BUILD_DIR"
          WORKSPACE_PATH=$(find ios -maxdepth 1 -name "*.xcworkspace" -type d | head -1)
          if [ -z "$WORKSPACE_PATH" ]; then
            echo "Error: No .xcworkspace found in ios/."
            ls -la ios/
            exit 1
          fi
          SCHEME_NAME=$(basename "$WORKSPACE_PATH" .xcworkspace)
          echo "Using workspace: $WORKSPACE_PATH, scheme: $SCHEME_NAME"
          xcode-project build-ipa \
            --workspace "$WORKSPACE_PATH" \
            --scheme "$SCHEME_NAME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - user@example.com   # ★ 要変更: ビルド通知を受け取るメールアドレスに
        notify:
          success: true
          failure: true
